# Generated by Django 4.2.1 on 2023-05-24 13:43

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApplicantsTable",
            fields=[
                (
                    "Applicants_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                (
                    "Applicants_name",
                    models.CharField(max_length=50, verbose_name="Name"),
                ),
                (
                    "Applicants_born_date",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Born Date"
                    ),
                ),
                (
                    "Applicants_user_emaill",
                    models.EmailField(
                        max_length=100, verbose_name=django.contrib.auth.models.User
                    ),
                ),
                (
                    "Applicants_password",
                    models.CharField(max_length=12, verbose_name="Password"),
                ),
                (
                    "Applicants_city",
                    models.CharField(max_length=50, verbose_name="City"),
                ),
                (
                    "Applicants_interestedin",
                    models.CharField(max_length=50, verbose_name="Interested in"),
                ),
                (
                    "Applicants_resume",
                    models.CharField(max_length=50, verbose_name="Resume"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobsTable",
            fields=[
                (
                    "jobs_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                (
                    "jobs_title",
                    models.CharField(max_length=50, verbose_name="Job Title"),
                ),
                (
                    "jobs_description",
                    models.TextField(max_length=200, verbose_name="Job Descriptions"),
                ),
                (
                    "jobs_requirements",
                    models.TextField(max_length=200, verbose_name="Job Requirements"),
                ),
                ("jobs_city", models.CharField(max_length=50, verbose_name="City")),
            ],
        ),
        migrations.CreateModel(
            name="MajorsTable",
            fields=[
                (
                    "majors_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                (
                    "majors_name",
                    models.CharField(max_length=50, verbose_name="Major Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompaniesTable",
            fields=[
                (
                    "companies_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                (
                    "companies_name",
                    models.CharField(max_length=50, verbose_name="Name"),
                ),
                (
                    "companies_description",
                    models.TextField(
                        max_length=200, verbose_name="Company Description"
                    ),
                ),
                (
                    "companies_email",
                    models.EmailField(max_length=100, verbose_name="Email"),
                ),
                (
                    "companies_password",
                    models.CharField(max_length=12, verbose_name="Password"),
                ),
                (
                    "companies_telephone",
                    models.CharField(max_length=25, verbose_name="Telephone"),
                ),
                (
                    "companies_website",
                    models.CharField(max_length=50, verbose_name="Website"),
                ),
                (
                    "companies_city",
                    models.CharField(max_length=50, verbose_name="City"),
                ),
                (
                    "companies_salary",
                    models.CharField(max_length=10, verbose_name="Salary"),
                ),
                (
                    "companies_Jobrequirement_description",
                    models.TextField(
                        max_length=200, verbose_name="Job Requirement Description"
                    ),
                ),
                (
                    "companies_applicantsid",
                    models.ManyToManyField(
                        default="",
                        to="product.applicantstable",
                        verbose_name="Applicants Id",
                    ),
                ),
                (
                    "companies_jobneeds",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.jobstable",
                        verbose_name="Job needs",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="applicantstable",
            name="Applicants_major",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.majorstable",
                verbose_name="Major",
            ),
        ),
    ]
