# Generated by Django 4.2.1 on 2023-05-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="applicantstable",
            old_name="Applicants_born_date",
            new_name="applicants_born_date",
        ),
        migrations.RenameField(
            model_name="applicantstable",
            old_name="Applicants_city",
            new_name="applicants_city",
        ),
        migrations.RenameField(
            model_name="applicantstable",
            old_name="Applicants_id",
            new_name="applicants_id",
        ),
        migrations.RenameField(
            model_name="applicantstable",
            old_name="Applicants_interestedin",
            new_name="applicants_interestedin",
        ),
        migrations.RenameField(
            model_name="applicantstable",
            old_name="Applicants_major",
            new_name="applicants_major",
        ),
        migrations.RenameField(
            model_name="applicantstable",
            old_name="Applicants_name",
            new_name="applicants_name",
        ),
        migrations.RenameField(
            model_name="applicantstable",
            old_name="Applicants_password",
            new_name="applicants_password",
        ),
        migrations.RenameField(
            model_name="applicantstable",
            old_name="Applicants_resume",
            new_name="applicants_resume",
        ),
        migrations.RenameField(
            model_name="applicantstable",
            old_name="Applicants_user_emaill",
            new_name="applicants_user_emaill",
        ),
    ]
